### ISSUE TITLE
Hessian bug

### ISSUE THREAD

**Issue by vlall** [Dallinger/bams#5]
This error terminates the leaner and happens on ~10% of runs. The higher the budget, the more likely you encounter the error. I've seen it happen in BALD more than the random strategy. It usually occurs in the 46th+ iteration of training.

My config was:
```NDIM = 1
POOL_SIZE = 500
BUDGET = 50
BASE_KERNELS = ["PER", "LIN", "K"]
DEPTH = 2
```
This occurs with RandomStrategy and BALD

```Traceback (most recent call last):
  File "learn_from_trial.py", line 47, in <module>
    learner.update(correct, guess)
  File "/Users/vlall/prog/dev/bams/bams/learners.py", line 60, in update
    self.models.update()
  File "/Users/vlall/prog/dev/bams/bams/models.py", line 142, in update
    model.update()
  File "/Users/vlall/prog/dev/bams/bams/models.py", line 35, in update
    self.gp.compute(self.data.x, yerr=self.yerr)
  File "/Users/vlall/.virtualenvs/bams/lib/python2.7/site-packages/george/gp.py", line 309, in compute
    self.solver.compute(self._x, yerr, **kwargs)
  File "/Users/vlall/.virtualenvs/bams/lib/python2.7/site-packages/george/solvers/basic.py", line 68, in compute
    self._factor = (cholesky(K, overwrite_a=True, lower=False), False)
  File "/Users/vlall/.virtualenvs/bams/lib/python2.7/site-packages/scipy/linalg/decomp_cholesky.py", line 91, in cholesky
    check_finite=check_finite)
  File "/Users/vlall/.virtualenvs/bams/lib/python2.7/site-packages/scipy/linalg/decomp_cholesky.py", line 40, in _cholesky
    "definite" % info)
numpy.linalg.linalg.LinAlgError: 2-th leading minor of the array is not positive definite```

Mac 10.14
Python 2.7.10

**Comment by vlall** [comment]
Changing the `BIC` to true avoid this bit of code, which is the purpose of the branch here: https://github.com/Dallinger/bams/tree/bic-true. 

See: https://github.com/Dallinger/bams/blob/2010737f5763ef5949f1b83c9917da089680174f/bams/models.py#L80
